### ISSUE TITLE
Using Docker Authenticated Pulls

### ISSUE THREAD

**Issue by fullflu** [fullflu/pydtr#3]
# WHY

ref: https://circleci.com/docs/2.0/private-images/

# TODO
- [x] create my account of dockerhub
- [x] add context in circleci (for pypi upload and docker login)
- [x] fix `.config.yml`
