### ISSUE TITLE
add examples

### ISSUE THREAD

**Issue by fullflu** [fullflu/pydtr#6]
# WHY

- There is no example in this project.
- It would also be helpful to show examples using pipeline, which enables us to deal with categorical independent variables.

# TODO

- [x] add tests using pipeline
- [x] fix a table in README

add notebooks
- [ ] continuous covariate and binary action
- [ ] continuous covariate and categorical action (using pipeline)
